#
#  Copyright 2016 Johns Hopkins University
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
version: "2"

services:

  rabbitmq:
    image: rabbitmq:latest
    container_name: osf-rabbitmq

  elasticsearch:
    image: elasticsearch:latest
    container_name: osf-elasticsearch

  tokumx:
    image: centerforopenscience/tokumx
    container_name: osf-tokumx
    env_file: .env
    ports:
      - "27017:27017"

  osf_api:
    image: dataconservancy/cos-osf-runtime:latest
    container_name: osf-api
    env_file: .env
    command: invoke -f /tmp/invoke.yaml apiserver --host=0.0.0.0
    links:
      - tokumx:tokumx
      - rabbitmq:rabbitmq
      - elasticsearch:elasticsearch
    depends_on:
      - cos_waterbutler
    expose:
      - 8000
    ports:
      - "8000:8000"

  osf_web:
    image: dataconservancy/cos-osf-runtime:latest
    container_name: osf-web
    env_file: .env
    command: invoke -f /tmp/invoke.yaml server --host=0.0.0.0
    links:
      - tokumx:tokumx
      - rabbitmq:rabbitmq
      - elasticsearch:elasticsearch
      - cos_fakecas:fakecas
    depends_on:
      - cos_waterbutler
    expose:
      - 5000
    ports:
      - "5000:5000"

  cos_fakecas:
    image: dataconservancy/cos-fakecas:latest
    container_name: osf-fakecas
    env_file: .env
    command: -dbaddress tokumx:27017 -host 0.0.0.0:8080 -osfhost ${docker.osf.host}
    links:
      - tokumx:tokumx
    expose:
      - 8080
    ports:
      - "8080:8080"

  cos_waterbutler:
    image: dataconservancy/cos-waterbutler:latest
    container_name: cos-waterbutler
    env_file: .env
    links:
      - elasticsearch:elasticsearch
    expose:
      - 7777
    ports:
      - "7777:7777"
